workspace:
  base: /go

pipeline:
  build:
    image: golang:1.5
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps
      - make vet
      - make build
      - make test

  publish:
    coverage:
      when:
        branch: master
    docker:
      username: $$DOCKER_USER
      password: $$DOCKER_PASS
      email: $$DOCKER_EMAIL
      repo: plugins/drone-rancher
      tag: latest
      when:
        branch: master
    docker:
      username: $$DOCKER_USER
      password: $$DOCKER_PASS
      email: $$DOCKER_EMAIL
      repo: plugins/drone-rancher
      tag: develop
      when:
        branch: develop
plugin:
  name: Rancher
  desc: Deploy or update a project on Rancher
  type: deploy
  image: plugins/drone-rancher
  labels:
    - rancher
    - docker
